# This ClusterSecretStore configures the External Secrets Operator to
# use the Kubernetes provider. This allows the operator to read secrets
# from other namespaces within the same cluster.

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      # The namespace where the source secret resides.
      # The External Secrets Operator will look for secrets here.
      secret:
        namespace: cert-manager
      # The service account that the operator will use to access the secret.
      auth:
        serviceAccountRef:
          name: external-secrets
          namespace: external-secrets
