# This secret stores the AWS credentials required by Cert-Manager's
# Route53 DNS01 challenge solver. The data fields must be Base64-encoded.
apiVersion: v1
kind: Secret
metadata:
  name: route53-acme-secret
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true" # annotation needed for reflector operator to be able to sync to other namespaces
  namespace: cert-manager
type: Opaque
data:
  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}